name: .NET Web App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: restore
      working-directory: Tailspin.SpaceGame.Web
      run: dotnet restore

    - name: build
      working-directory: Tailspin.SpaceGame.Web
      run: dotnet build
      
    - name: test
      working-directory: Tailspin.SpaceGame.Web.Tests
      run: dotnet test

    - name: publish
      working-directory: Tailspin.SpaceGame.Web
      run: dotnet publish Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj -c Release -o ./SpaceGame

    - run: ls -R

    - name: upload-artifacts
      uses: actions/upload-artifact@v2
      with:
        name: spacegame
        path: ./SpaceGame
      
  dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: download-artifacts
      uses: actions/download-artifact@v2
      with:
        name: spacegame

    - run: ls -R

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to PROD Azure webapp using OIDC'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: tailspin-spacegame-web # Replace with your app name
        package: spacegame
